---
- name: urotaxi application playbook
  hosts: all
  vars:
    TOMCAT_DOWNLOAD_URL: "https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz"
    TOMCAT_HOME_DIR: "/u01/middleware/apache-tomcat-9.0.70"
  tasks:
    - name: install jdk11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
    - name: create tomcat middleware directoty
      file:
        path: /u01/middleware
        state: directory
        owner: ubuntu
        group: ubuntu
      become: yes
      become_method: sudo
    - name: download tomcat9 
      get_url:
        url: "{{TOMCAT_DOWNLOAD_URL}}"
        dest: /u01/middleware
    - name: unarchive tomcat9
      unarchive:
        src: /u01/middleware/apache-tomcat-9.0.70.tar.gz
        dest: /u01/middleware
        remote_src: true
    - name: find jdk home
      shell: "readlink -f $(which java) | sed 's/bin.*//g'"
      register: JDK_HOME
    - name: run tomcta as service file
      template: 
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
      become: yes
      become_method: sudo
      notify:
        - tomcatrelaoded
    - name: install python3-pymysql
      apt:
        name: python3-pymysql
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
    - name: install mysql client tool
      apt:
        name: mysql-client-8.0
        state: present
        update_cache: yes
      become: yes
      become_method: sudo
    - name: copy db schema file
      copy: 
        src: "{{ lookup('env', 'WORKSPACE') }}/src/main/db/urotaxidb.sql"
        dest: /tmp/
    - name: create schema
      community.mysql.mysql_db:
        state: import
        name: all
        target: /temp/urotaxidb.sql
        login_host: "{{ lookup('env', 'DB_HOST') }}"
        login_user: "{{ lookup('env', 'UROTAXI_DB_USER') }}"
        login_password: "{{ lookup('env', 'UROTAXI_DB_PSW') }}"
    - name: deploy 
      copy: 
        src: "{{ lookup('env', 'WORKSPACE') }}/target/urotaxi.war"
        dest: /u01/middleware/apache-tomcat-9.0.70/webapps/
      notify:
        - tomcatrestarted
  handlers:
    - name: tomcatrelaoded
      service:
        name: tomcat
        state: reloaded
        enabled: yes
      become: yes
      become_method: sudo
    - name: tomcatrestarted
      service:
        name: tomcat
        state: restarted
      become: yes
      become_method: sudo